name: Android NDK Cross Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK: ${{ github.workspace }}/android-ndk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build meson python3-pip libglib2.0-dev
        pip3 install meson

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip android-ndk-r25c-linux.zip
        mv android-ndk-r25c $ANDROID_NDK

    - name: Generate Meson cross-file
      run: |
        TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin
        echo "[binaries]" > meson-cross-android-arm64.txt
        echo "c = '$TOOLCHAIN/aarch64-linux-android21-clang'" >> meson-cross-android-arm64.txt
        echo "cpp = '$TOOLCHAIN/aarch64-linux-android21-clang++'" >> meson-cross-android-arm64.txt
        echo "ar = '$TOOLCHAIN/llvm-ar'" >> meson-cross-android-arm64.txt
        echo "strip = '$TOOLCHAIN/llvm-strip'" >> meson-cross-android-arm64.txt
        echo "pkgconfig = 'pkg-config'" >> meson-cross-android-arm64.txt
        echo "" >> meson-cross-android-arm64.txt
        echo "[host_machine]" >> meson-cross-android-arm64.txt
        echo "system = 'android'" >> meson-cross-android-arm64.txt
        echo "cpu_family = 'aarch64'" >> meson-cross-android-arm64.txt
        echo "cpu = 'aarch64'" >> meson-cross-android-arm64.txt
        echo "endian = 'little'" >> meson-cross-android-arm64.txt

    - name: Configure Meson (cross build)
      run: |
        meson setup builddir \
          --cross-file=meson-cross-android-arm64.txt \
          -Dandroid_ndk_path=$ANDROID_NDK \
          -Dprefix=/usr \
          -Ddefault_library=static

    - name: Build project
      run: |
        meson compile -C builddir

    - name: Run tests
      run: |
        meson test -C builddir

